### ISSUE TITLE
Error code -2: What does it mean?

### ISSUE THREAD

**Issue by gwahyzark** [Slaynash/MelonWiki#33]
Here is my console log in its entirety: [17:28:37.819] Assembly Generation Needed!
[17:28:37.819] Downloading Il2CppDumper
[17:28:37.822] C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppDumper already contains required version, skipping download
[17:28:37.829] Downloading Il2CppAssemblyUnhollower
[17:28:37.830] C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppAssemblyUnhollower already contains required version, skipping download
[17:28:37.830] Downloading Unity Dependencies
[17:28:37.831] C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\UnityDependencies already contains required version, skipping download
[17:28:37.837] Executing Il2CppDumper...
[17:28:37.840] "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppDumper\Il2CppDumper.exe" "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\GameAssembly.dll" "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data\il2cpp_data\Metadata\global-metadata.dat"
[17:28:38.351] Initializing metadata...
[17:28:40.261] Metadata Version: 24.2
[17:28:40.261] Initializing il2cpp file...
[17:28:40.290] Il2Cpp Version: 24.2
[17:28:40.291] Searching...
[17:28:40.677] CodeRegistration : 181bcb288
[17:28:40.678] MetadataRegistration : 181bceda0
[17:28:40.732] System.OverflowException: Array dimensions exceeded supported range.
[17:28:40.733]    at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 198
[17:28:40.733]    at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 100
[17:28:40.734]    at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 67
[17:28:40.734]    at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 190
[17:28:40.735] ERROR: An error occurred while processing.
[17:28:40.741] Executing Il2CppAssemblyUnhollower...
[17:28:40.742] "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppAssemblyUnhollower\AssemblyUnhollower.exe" "--input=C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppDumper\DummyDll" "--output=C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\Il2CppAssemblyUnhollower\Output" "--mscorlib=C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Managed\mscorlib.dll" "--unity=C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\AssemblyGenerator\UnityDependencies" "--gameassembly=C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\GameAssembly.dll" "--blacklist-assembly=Mono.Security" "--blacklist-assembly=Newtonsoft.Json" "--blacklist-assembly=Valve.Newtonsoft.Json"
[17:28:40.966] Reading assemblies... 
[17:28:41.147] Done in 00:00:00.1808469
[17:28:41.148] Computing renames... 
[17:28:41.173] Done in 00:00:00.0259965
[17:28:41.173] Creating typedefs... 
[17:28:41.174] Done in 00:00:00.0003356
[17:28:41.174] Computing struct blittability... 
[17:28:41.174] Done in 00:00:00.0003754
[17:28:41.175] Filling typedefs... 
[17:28:41.175] Done in 00:00:00.0008318
[17:28:41.176] Filling generic constraints... 
[17:28:41.176] Done in 00:00:00.0008470
[17:28:41.177] Creating members... 
[17:28:41.177] Done in 00:00:00.0002418
[17:28:41.178] Scanning method cross-references... 
[17:28:41.228] Done in 00:00:00.0526549
[17:28:41.229] Finalizing method declarations... 
[17:28:41.230] Done in 00:00:00.0022000
[17:28:41.231] 0 total potentially dead methods
[17:28:41.231] Filling method parameters... 
[17:28:41.232] Done in 00:00:00.0009204
[17:28:41.233] Creating static constructors... 
[17:28:41.235] Done in 00:00:00.0002998
[17:28:41.236] Creating value type fields... 
[17:28:41.237] Done in 00:00:00.0021072
[17:28:41.238] Creating enums... 
[17:28:41.239] Done in 00:00:00.0012893
[17:28:41.241] Creating IntPtr constructors... 
[17:28:41.242] Done in 00:00:00.0056477
[17:28:41.246] Creating type getters... 
[17:28:41.248] Done in 00:00:00.0012695
[17:28:41.250] Creating non-blittable struct constructors... 
[17:28:41.251] Done in 00:00:00.0010999
[17:28:41.252] Creating generic method static constructors... 
[17:28:41.253] Done in 00:00:00.0023235
[17:28:41.254] Creating field accessors... 
[17:28:41.255] Done in 00:00:00.0010022
[17:28:41.256] Filling methods... 
[17:28:41.257] Done in 00:00:00.0042209
[17:28:41.258] Generating implicit conversions... 
[17:28:44.210] Done in 00:00:02.9589878
[17:28:44.215] Failed to Execute Il2CppAssemblyUnhollower!
[17:28:44.229] [Error] Assembly Generator exited with code -2

**Comment by Slaynash** [comment]
Hello
Please keep the MelonWiki issues related to the MelonWiki itself.
To get some help about BTD6 modding, please either use [the MelonLoader Discord](https://discord.gg/2Wn3N2P), or [the BTD6 Modding Discord](https://discord.gg/SeRH8xQ5mQ).
